### ISSUE TITLE
ImportError: cannot import name 'url' from 'django.conf.urls' 

### ISSUE THREAD

**Issue by patrickuhlmann** [juntagrico/juntagrico-crowdfunding#1]
When I tried using this extension with Juntagrico 1.5.7, I got the following error:
```
#8 72.82   File "/usr/local/lib/python3.10/site-packages/juntagrico_crowdfunding/urls.py", line 3, in <module>
#8 72.82     from django.conf.urls import url
#8 72.82 ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.10/site-packages/django/conf/urls/__init__.py)
```

I guess url needs to be replaced with re_path here: https://github.com/juntagrico/juntagrico-crowdfunding/blob/main/juntagrico_crowdfunding/urls.py

**Comment by pascalfree** [comment]
Yes that was one of multiple issues.
I now upgraded the addon to juntagrico 1.5 / Django 4.0.
Only tested it roughly. If you want to use it in production I recommend testing it a bit further.
There is one issue: Non-Members can not open the crowdfunding page, because of an issue in the juntagrico menu. That requires a change in juntagrico itself.
